apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: <YOUR-DOCKER-IMAGE-PATH-FOR-API>
        env:
        - name: REDIS_HOST
          value: redis
        ports:
        - containerPort: 80
